name: hyperbolic-vae
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pytorch-lightning
  - plotly
  - tensorboard
  - pandas
  - ruff
  - pytest
  - isort
  - pip
  - pip:
    - git+https://github.com/geoopt/geoopt.git@a41c09b