[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hyperbolic_vae"
version = "0.1.0"
description = ""
authors = ["William Grisaitis <wgrisaitis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
torch = {version = "2.2.1", source = "pytorch-cpu"}
pytorch-lightning = "2.2.1"
torchvision = {version = "0.17.1", source = "pytorch-cpu"}
termcolor = "2.4.0"
kaleido = "0.2.1"
numpy = "^1.23"
pandas = "^2"
matplotlib = "^3.7"
plotly = "^5.16"
tqdm = "^4.66"
torch-adata = "0.0.24"
universal_pathlib = "0.2.1"
fsspec = "2023.6.0"
imageio = "^2.34.0"
geoopt = {git = "https://github.com/geoopt/geoopt.git", rev = "a41c09b7"}
# pvae = { path = "../pvae", develop = true }
pyarrow = "^15.0.2"

[tool.poetry.dev-dependencies]
black = "*"
ruff = "*"
isort = "*"
pytest = "*"
ipython = "*"
tensorboard = "2.16.2"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "supplemental"

[tool.black]
target-version = ['py311']
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/pytorch
  | ^/python-docs-samples
  | ^/vertex_samples
  | ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.ruff]
target-version = "py311"
fix = true
line-length = 120
respect-gitignore = true
lint.ignore = ["F401"]
lint.ignore-init-module-imports = true
lint.unfixable = ["F401"]
