[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "hyperbolic_vae"
version = "0.1.0"
description = ""
authors = ["William Grisaitis <wgrisaitis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2"
pytorch-lightning = "^2"
torchvision = "*"
numpy = "^1.23"
pandas = "^2"
matplotlib = "^3.7"
plotly = "^5.16"
scikit-learn = "^1.3"
scikit-image = "^0.21"
scipy = "^1.11"
tqdm = "^4.66"
# geoopt = { git = "https://github.com/geoopt/geoopt.git", rev = "a41c09b7" } # as of august 2023
# pvae = { path = "../pvae", develop = true }

[tool.poetry.dev-dependencies]
black = "^21.9"
ruff = "^0.2"
isort = "^5.9"

[tool.black]
line-length = 110
target-version = ['py310']
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/pytorch
  | ^/python-docs-samples
  | ^/vertex_samples
  | ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.ruff]
target-version = "py310"
fix = true
ignore-init-module-imports = true
line-length = 120
unfixable = ["F401"]
ignore = ["F401"]
respect-gitignore = true
