name: base
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio
  - cpuonly
  - pytorch-lightning=2.2.1
  - tensorboard
  - pandas
  - ruff
  - pytest
  - isort
  - pip
  - ipython
  - pip:
    - poetry
    - termcolor
    - plotly
    - kaleido
    - tqdm
    - torch-adata
    - universal_pathlib
    - fsspec
    - git+https://github.com/geoopt/geoopt.git@a41c09b